set -g mouse on
set -g default-terminal "tmux-256color"

set -g @plugin_manager_path '~/.config/tmux/plugins/'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

source ~/.config/tmux/plugins/theme/theme.conf
source ~/.config/tmux/keybind.conf

run '~/.config/tmux/plugins/tpm/tpm'

